### ISSUE TITLE
Updating a PDI object

### ISSUE THREAD

**Issue by niiick1** [Soontao/pdi-util#14]
Hi @Soontao,

Is it possible to update a file, like a mashup or BO in a PDI solution through the CLI? 

From the features, it seems not supported now, but is it feasible?

**Comment by Soontao** [comment]
Hello @niiick1 

It’s totally feasible, :), in technical, clients could upload any files to the XREP backend, even they can not be activated. 

But now, I’m very cautiously add WRITE features to this cli tool, because there are some source code are generated by PDI, and I don’t know the PDI implementation details, so it’s a dangerous thing to WRITE items to server.
For example, if the pdi-cli want to upload a BO item to XREP, it will be a easily task, just write the content is enough, but if the cli want to upload a BO with some ABSL scripts, it will be a much complex task, because the ABSL scripts have the ‘mass-enable’ or ‘not-mass-enable’ mode, so the cli should process the different modes correctly. If there are some features the PDI implemented but the cli tool don’t know, as a result, the cli can not process them correctly, and the uploaded item also can not work.
In addition, UI related items are so complicated that only the PDI can process them correctly .

Thanks

**Comment by niiick1** [comment]
Sure, your concerns are totally valid.

It's been a while I have worked with PDI, but our team still makes some integrations with C4C every now and then and it's always weird how to integrate the development flow on PDI due to being so restricted to the IDE. So, we have an interest on how to make development more detached from PDI and enable automation with other tools. 

For now, I'm mostly interested in publishing HTML mashups to the solution, but I have no idea what is stored on XREP or how the file is structured.

As you said , PDI is really a black box as it's difficult to know what happens there. Do you have any knowledge on how to make this work?

Also, do you have any contact with the core team? I'm interested in talking about extensibility outside PDI, like your tool does.

**Comment by Soontao** [comment]
Thanks for your long descriptions. 

In fact, the reason why I create this tool, is that our team (SAP IBSO China) meet some issues on PDI package assembly: 
* the assembly processs wiil take several hours for huge size solution, if something wrong, developers shuold do modification, activation & assembly again, sometimes my team-member/colleagues must check the assembly status in mid-night.
* without version management (for external developers), we want to use `git` to do `backup`, `diff` even `code review`
* some code static checks, e.g. name convention.

I dont have the direct communication with the PDI core team, in fact, I'm not sure they are active on development or busy on incidents.

This project is totally based on `reverse engineering`, I use the [fiddler](https://www.telerik.com/fiddler) trace all network traffic between `PDI` & `Netweaver Server`, analysis traffic. Then, when I want to the some specific operation, send the corresponding http request is enough. In fact, the communication protocol between `PDI` & `Netweaver` is based on HTTP - json format, easy to be analysis.

I'm not sure your cases, maybe you want to re-use some mashup which created by PDI, just assemble the package which include the re-useable mashup & deploy to it the target tenant is enough. But, if your mashups are created by UI/frontend, PDI can not process them, they are worked in different `layers`. Same, the configurations also are not controlled by PDI. for anything created from UI/frontend, they are new requirement for product, just create your idea -- `I want to transport mashup between tenants` in [customer influence](https://influence.sap.com/sap/ino/), then wait for years haha :).

Thanks

**Comment by Soontao** [comment]
Closed by no more details
